version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:  
  node_sample_job:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: yarn test
          name: running test cases
      - run:
          command: npm build
          name: Building the code          
workflows:
  node_workflow:
    jobs:
      - node_sample_job
    